import { StyleSheet } from "react-native";
import {
    BORDER_RADIUS,
    COLORS,
    SHADOWS,
    SPACING,
    TYPOGRAPHY,
} from "../../../../constants/theme.constants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  centerContent: {
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    fontSize: TYPOGRAPHY.fontSize.lg,
    color: COLORS.textSecondary,
    marginBottom: SPACING.md,
  },
  backButton: {
    padding: SPACING.sm,
  },
  backButtonText: {
    color: COLORS.primary,
    fontWeight: "bold",
  },
  headerImageContainer: {
    width: "100%",
    height: 220,
    position: "relative",
    overflow: "visible",
  },
  headerImage: {
    width: "100%",
    height: "100%",
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  navbar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.sm,
    zIndex: 10,
  },
  navButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    ...SHADOWS.small,
  },
  chatBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 3,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#fff",
  },
  chatBadgeText: {
    color: "#fff",
    fontSize: 9,
    fontWeight: "700",
    lineHeight: 11,
  },
  disabledAction: {
    opacity: 0.5,
  },
  navActions: {
    flexDirection: "row",
    gap: SPACING.sm,
  },
  headerContent: {
    position: "absolute",
    bottom: 6,
    left: 40,
    right: SPACING.lg,
  },
  badgeContainer: {
    flexDirection: "row",
    gap: SPACING.sm,
    marginBottom: SPACING.sm,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: "rgba(12, 10, 9, 0.42)",
    borderWidth: 1,
    borderColor: "rgba(249, 231, 165, 0.9)",
    flexDirection: "row",
    alignItems: "center",
  },
  statusBadgeCompleted: {
    backgroundColor: "rgba(21, 128, 61, 0.95)",
    borderColor: "#86EFAC",
    borderWidth: 2,
    shadowColor: "#15803D",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  statusText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFF3C4",
  },
  statusTextCompleted: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  title: {
    fontSize: 25,
    fontWeight: "800",
    color: "#fff",
    fontFamily: TYPOGRAPHY.fontFamily.display,
    marginBottom: SPACING.sm,
    textShadowColor: "rgba(0,0,0,0.82)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  metaText: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    fontWeight: "500",
  },
  metaDivider: {
    width: 1,
    height: 14,
    backgroundColor: "rgba(255,255,255,0.4)",
    marginHorizontal: SPACING.md,
  },
  memberGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  memberAvatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  memberAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#fff",
    backgroundColor: "#fff",
  },
  memberInitialAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#fff",
    backgroundColor: "rgba(201,162,39,0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  memberInitialText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
  },
  memberOverflowChip: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: 6,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#fff",
    backgroundColor: "rgba(255,255,255,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  memberOverflowChipText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "800",
  },
  memberCountText: {
    color: "rgba(255,255,255,0.95)",
    fontSize: 13,
    fontWeight: "700",
  },
  content: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 14,
  },
  scrollContent: {
    paddingBottom: 44,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
  },
  dayContainer: {
    marginBottom: SPACING.lg,
  },
  dayHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
  },
  dayNumberContainer: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: BORDER_RADIUS.md,
    marginRight: SPACING.sm,
  },
  dayNumber: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  dayLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.border,
  },
  timelineContainer: {
    paddingHorizontal: SPACING.lg,
    position: "relative",
  },
  timelineLine: {
    position: "absolute",
    left: 36,
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: COLORS.border,
  },
  timelineItems: {
    gap: SPACING.md,
    paddingLeft: 12,
  },
  timelineItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  travelSegment: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    marginLeft: 26,
  },
  verticalDashedLine: {
    position: "absolute",
    left: 0,
    top: -10,
    bottom: -10,
    width: 2,
    borderLeftWidth: 2,
    borderColor: "#D1D5DB",
    borderStyle: "dashed",
    zIndex: -1,
  },
  travelBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 14,
    gap: 6,
  },
  travelText: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
  },
  /**
   * Outer card shell: shadow + rounded rect (no overflow:hidden here — avoids clipped shadow
   * looking like a second rectangle under the rounded corners).
   */
  timelineCardShadowWrap: {
    flex: 1,
    marginLeft: 12,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: COLORS.white,
    position: "relative",
    ...SHADOWS.small,
  },
  /** Inner clip for swipe + solid fill; matches outer radius. */
  timelineSwipeInner: {
    borderRadius: BORDER_RADIUS.lg,
    overflow: "hidden",
    backgroundColor: COLORS.white,
  },
  timelineDeleteActionWrap: {
    width: 80,
    flexDirection: "column",
    alignSelf: "stretch",
  },
  timelineDeleteAction: {
    flex: 1,
    minHeight: 72,
    backgroundColor: "#DC2626",
    justifyContent: "center",
    alignItems: "center",
    borderTopRightRadius: BORDER_RADIUS.lg,
    borderBottomRightRadius: BORDER_RADIUS.lg,
  },
  timelineDeleteActionLabel: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: COLORS.primary,
    position: "absolute",
    left: -19,
    zIndex: 1,
  },
  /** Row content inside swipe (no extra radius/shadow — outer wrap handles that). */
  itemCardInner: {
    flexDirection: "row",
    alignItems: "center",
    padding: SPACING.sm,
    backgroundColor: COLORS.white,
  },
  itemImage: {
    width: 60,
    height: 60,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.backgroundSoft,
  },
  itemContent: {
    flex: 1,
    paddingHorizontal: SPACING.sm,
    justifyContent: "center",
  },
  itemName: {
    fontSize: 17,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  itemAddress: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: 4,
  },
  itemFooter: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  itemTimeInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.accentSubtle,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: BORDER_RADIUS.sm,
  },
  itemTime: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.primary,
  },
  itemNote: {
    fontSize: 13,
    color: COLORS.textSecondary,
    fontStyle: "italic",
    maxWidth: 100,
  },
  itemActions: {
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    flexShrink: 0,
  },
  checkInButton: {
    padding: 4,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: SPACING.xl,
    gap: SPACING.sm,
  },
  emptyStateText: {
    color: COLORS.textTertiary,
    fontSize: 14,
  },
  addItemsButton: {
    marginTop: SPACING.sm,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.full,
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.accent,
  },
  addItemsButtonText: {
    color: COLORS.primary,
    fontWeight: "600",
    fontSize: 14,
  },
  addSmallButton: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginLeft: 24,
    gap: 4,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(201,162,39,0.55)",
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: "rgba(201,162,39,0.08)",
    paddingVertical: 8,
    paddingHorizontal: 10,
    alignSelf: "stretch",
    minHeight: 44,
  },
  addSmallButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.primary,
  },
  quickActionsRow: {
    flexDirection: "row",
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
    gap: 8,
    flexWrap: "nowrap",
  },
  quickActionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 999,
    backgroundColor: "#8C6D42",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    position: "relative",
  },
  /** Người đã rời nhóm: cùng CTA tài chính/chốt kế hoạch nhưng chỉ mở xem thành viên & tiến độ (read-only) */
  quickActionButtonReadOnly: {
    borderWidth: 1,
    borderColor: "rgba(255, 248, 231, 0.4)",
  },
  quickActionText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFF8E7",
  },
  quickActionBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#fff",
  },
  quickActionBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
  },
  travelInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginLeft: 24,
    marginTop: 2,
    marginBottom: 8,
  },
  travelInfoText: {
    fontSize: 12,
    color: "#7C6A3A",
    fontWeight: "500",
  },
  pilgrimTag: {
    alignSelf: "flex-start",
    marginBottom: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(201,162,39,0.14)",
    borderWidth: 1,
    borderColor: "rgba(201,162,39,0.4)",
  },
  pilgrimTagText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#7B5C11",
  },
  addNextDayButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: SPACING.lg,
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    backgroundColor: COLORS.accentSubtle,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 2,
    borderColor: COLORS.accent,
    borderStyle: "dashed",
    gap: SPACING.sm,
  },
  addNextDayButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.accent,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 40,
  },
  modalHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.textPrimary,
  },
  modalClose: {
    fontSize: 16,
    color: COLORS.primary,
  },
  itemDetailModalTitleCenter: {
    flex: 1,
    textAlign: "center",
    marginHorizontal: 4,
  },
  itemDetailModalHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
    minWidth: 72,
  },
  siteItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    marginBottom: 12,
    ...SHADOWS.small,
  },
  siteItemImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: COLORS.backgroundSoft,
  },
  siteItemContent: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  siteItemName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  siteItemAddress: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  tabContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    marginBottom: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  activeTabButton: {
    borderBottomColor: COLORS.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  activeTabText: {
    color: COLORS.primary,
  },
  timeInputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: SPACING.xs,
  },
  timeInputDescription: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginBottom: SPACING.lg,
  },
  routeInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.xs,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    backgroundColor: COLORS.accentSubtle,
    borderRadius: BORDER_RADIUS.md,
    marginBottom: SPACING.md,
  },
  routeInfoText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    fontWeight: "500",
    flex: 1,
  },
  timeInputContainer: {
    marginBottom: SPACING.md,
  },
  timeInputFieldLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  timeInputHint: {
    fontSize: 12,
    color: COLORS.textTertiary,
    marginBottom: SPACING.xs,
    fontStyle: "italic",
  },
  timePickerButton: {
    backgroundColor: COLORS.white,
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
  },
  timePickerButtonText: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.primary,
    flex: 1,
    textAlign: "center",
    letterSpacing: 2,
  },
  durationValueText: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textAlign: "center",
    marginVertical: SPACING.md,
  },
  slider: {
    width: "100%",
    height: 40,
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  sliderLabelText: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  noteInputContainer: {
    marginBottom: SPACING.md,
  },
  noteInput: {
    marginTop: SPACING.xs,
    backgroundColor: COLORS.backgroundSoft,
    borderRadius: BORDER_RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    fontSize: 14,
    color: COLORS.textPrimary,
    minHeight: 80,
    maxHeight: 120,
  },
  confirmButton: {
    backgroundColor: COLORS.accent,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    alignItems: "center",
    marginTop: SPACING.lg,
    ...SHADOWS.small,
  },
  saveTimeButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: "600",
  },
  nearbyPlaceCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    ...SHADOWS.small,
  },
  nearbyPlaceCategoryBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    marginRight: SPACING.sm,
  },
  nearbyPlaceCategoryText: {
    fontSize: 20,
  },
  nearbyPlaceContent: {
    flex: 1,
  },
  nearbyPlaceName: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  nearbyPlaceAddress: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  nearbyPlaceMeta: {
    fontSize: 12,
    color: COLORS.textTertiary,
  },
  nearbyPlaceDescription: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 4,
    fontStyle: "italic",
  },
  nearbyPlaceSelectBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: COLORS.accent,
    borderRadius: BORDER_RADIUS.sm,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginTop: 8,
    alignSelf: "flex-start",
  },
  nearbyPlaceSelectBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#fff",
  },
  itemDetailHero: {
    borderTopLeftRadius: BORDER_RADIUS.lg,
    borderTopRightRadius: BORDER_RADIUS.lg,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: "hidden",
    height: 236,
    marginBottom: 0,
    position: "relative",
    justifyContent: "flex-end",
  },
  itemDetailImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
  },
  itemDetailOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  itemDetailHeroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  itemDetailHeroContent: {
    padding: SPACING.md,
    paddingBottom: SPACING.md,
  },
  itemDetailTypeBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.92)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: BORDER_RADIUS.full,
    marginBottom: SPACING.sm,
  },
  itemDetailTypeBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  itemDetailSiteName: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "800",
    letterSpacing: -0.3,
    marginBottom: SPACING.sm,
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  itemDetailHeroAddressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  itemDetailHeroAddressText: {
    flex: 1,
    fontSize: 13,
    color: "rgba(255,255,255,0.95)",
    lineHeight: 18,
    fontWeight: "500",
  },
  itemDetailContentWrap: {
    paddingHorizontal: 0,
    paddingBottom: SPACING.xl,
  },
  itemDetailScheduleCard: {
    backgroundColor: "#FFFEFA",
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: "#EFE6D7",
    ...SHADOWS.small,
  },
  itemDetailScheduleCardAttached: {
    marginTop: 0,
    marginBottom: SPACING.md,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopWidth: 0,
  },
  itemDetailScheduleCardTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#3F3A2F",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    marginBottom: SPACING.md,
  },
  itemDetailTravelBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    backgroundColor: "rgba(217, 119, 6, 0.08)",
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.sm,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.2)",
  },
  itemDetailTravelBannerText: {
    flex: 1,
    fontSize: 14,
    color: COLORS.textPrimary,
    fontWeight: "600",
    lineHeight: 20,
  },
  itemDetailInfoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  itemDetailInfoRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  itemDetailInfoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: "rgba(140, 109, 66, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  itemDetailInfoLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  itemDetailInfoValue: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    lineHeight: 22,
  },
  itemDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  itemDetailRowText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    flexShrink: 1,
  },
  itemDetailDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: SPACING.md,
  },
  itemDetailActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: SPACING.sm,
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    ...SHADOWS.small,
  },
  itemDetailActionText: {
    fontSize: 15,
    fontWeight: "500",
    color: COLORS.textPrimary,
  },
  savedNearbyPlaceRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: SPACING.sm,
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.sm,
    marginBottom: 4,
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.sm,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.accent,
  },
  savedNearbyPlaceEmoji: {
    fontSize: 18,
    lineHeight: 24,
  },
  savedNearbyPlaceName: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  savedNearbyPlaceAddress: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
});

export default styles;
