import { Platform, StyleSheet } from "react-native";
import { COLORS, SPACING } from "../../../../constants/theme.constants";

export const exploreFilterModalStyles = StyleSheet.create({
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 1000,
    justifyContent: "flex-end",
  },
  overlayDismiss: {
    flex: 1,
  },
  keyboardView: {
    maxHeight: "88%",
  },
  scrollContent: {
    paddingBottom: SPACING.lg,
  },
  modalContent: {
    backgroundColor: COLORS.accentSubtle,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    paddingTop: 20,
    maxHeight: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1A1A1A",
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
  },
  filterSection: {
    marginBottom: 24,
  },
  filterSectionLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: "#4B5563",
    marginBottom: 12,
  },
  regionGrid: {
    flexDirection: "row",
    alignItems: "center",
  },
  regionChip: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 6,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.05)",
    alignItems: "center",
  },
  regionChipSpacing: {
    marginRight: 8,
  },
  regionChipActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  regionChipText: {
    fontSize: 12,
    color: "#4B5563",
    fontWeight: "600",
    textAlign: "center",
  },
  regionChipTextActive: {
    color: COLORS.primaryDark,
  },
  typeWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  typeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
  },
  typeChipActive: {
    backgroundColor: COLORS.accent,
    borderColor: COLORS.accent,
  },
  typeChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4B5563",
  },
  typeChipTextActive: {
    color: COLORS.primaryDark,
  },
  optionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#F9FAFB",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  optionRowActive: {
    borderColor: COLORS.accent,
    backgroundColor: "rgba(236, 182, 19, 0.10)",
  },
  optionRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  optionTextWrap: {
    flex: 1,
    paddingRight: 10,
  },
  optionIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  optionRowTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  optionRowSub: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 2,
  },
  toggleBase: {
    width: 48,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#E5E7EB",
    padding: 2,
    marginLeft: 10,
  },
  toggleBaseActive: {
    backgroundColor: COLORS.accent,
  },
  toggleCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleCircleActive: {
    alignSelf: "flex-end",
  },
  modalFooterActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    paddingTop: 8,
  },
  resetBtn: {
    width: 110,
    height: 56,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  resetBtnText: {
    color: "#4B5563",
    fontSize: 16,
    fontWeight: "700",
  },
  applyBtn: {
    flex: 1,
    backgroundColor: COLORS.accent,
    height: 56,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  applyBtnText: {
    color: COLORS.primaryDark,
    fontSize: 16,
    fontWeight: "800",
  },
});
