import { StyleSheet } from "react-native";
import {
  BORDER_RADIUS,
  COLORS,
  SHADOWS,
  SPACING,
  TYPOGRAPHY,
} from "../../../../../constants/theme.constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  countBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.lg,
    ...SHADOWS.small,
    marginBottom: SPACING.lg,
  },
  countText: {
    fontSize: TYPOGRAPHY.fontSize.md,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.textPrimary,
  },
  selectedSection: {
    marginBottom: SPACING.lg,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.fontSize.md,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textPrimary,
    marginBottom: SPACING.sm,
  },
  siteCard: {
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    borderRadius: 18,
    padding: 11,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    position: "relative",
    overflow: "visible",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  siteOrderBadge: {
    position: "absolute",
    top: -8,
    left: 12,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#D4AF37",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  siteOrderText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  siteCardContent: {
    flex: 1,
    marginRight: 40,
    paddingTop: 4,
  },
  siteTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  siteImageWrap: {
    position: "relative",
  },
  siteImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  siteThumbnail: {
    width: 50,
    height: 50,
    borderRadius: BORDER_RADIUS.md,
    marginRight: SPACING.sm,
  },
  siteInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  siteName: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    lineHeight: 21,
    marginBottom: 4,
  },
  siteAddressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  siteAddress: {
    fontSize: 12,
    color: COLORS.textSecondary,
    lineHeight: 16,
    flex: 1,
  },
  siteTagsScroller: {
    maxHeight: 22,
    marginBottom: 6,
    marginTop: 2,
  },
  siteTagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingRight: 8,
  },
  typeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(217,119,6,0.12)",
    borderWidth: 1,
    borderColor: "rgba(217,119,6,0.25)",
  },
  typeBadgeText: {
    fontSize: 10,
    color: "#B45309",
    fontWeight: "700",
  },
  patronBadge: {
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(30, 77, 107, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(30, 77, 107, 0.2)",
    maxWidth: 190,
  },
  patronBadgeText: {
    fontSize: 10,
    color: "#1E4D6B",
    fontWeight: "700",
  },
  removeButton: {
    position: "absolute",
    top: 11,
    right: 11,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  addSection: {
    marginBottom: SPACING.lg,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.white,
    paddingVertical: SPACING.md,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 2,
    borderColor: "#D4AF37",
    borderStyle: "dashed",
  },
  addButtonText: {
    fontSize: TYPOGRAPHY.fontSize.md,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: "#D4AF37",
  },
  favoritesSection: {
    marginBottom: SPACING.lg,
  },
  favoriteCard: {
    width: 120,
    marginRight: SPACING.md,
    backgroundColor: COLORS.white,
    borderRadius: BORDER_RADIUS.lg,
    overflow: "hidden",
    ...SHADOWS.small,
  },
  favoriteImage: {
    width: "100%",
    height: 100,
  },
  favoriteName: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    color: COLORS.textPrimary,
    padding: SPACING.sm,
    minHeight: 40,
  },
  favoriteAddIcon: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: COLORS.white,
    borderRadius: 12,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: TYPOGRAPHY.fontSize.lg,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textPrimary,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.white,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    margin: SPACING.lg,
    borderRadius: BORDER_RADIUS.lg,
    ...SHADOWS.small,
  },
  searchInput: {
    flex: 1,
    fontSize: TYPOGRAPHY.fontSize.md,
    color: COLORS.textPrimary,
    paddingVertical: SPACING.xs,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  searchResultCard: {
    marginBottom: 12,
    marginHorizontal: SPACING.lg,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.06)",
    borderRadius: 18,
    padding: 11,
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    position: "relative",
    overflow: "hidden",
  },
  searchResultCardSelected: {
    backgroundColor: "#FFF9F3",
    borderColor: "rgba(212, 175, 55, 0.3)",
  },
  searchResultPressable: {
    flex: 1,
  },
  searchResultTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  searchResultImageWrap: {
    position: "relative",
  },
  searchResultImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
  },
  searchResultInfo: {
    flex: 1,
    marginLeft: 12,
    marginRight: 40,
    minWidth: 0,
  },
  searchResultName: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    lineHeight: 21,
    marginBottom: 4,
  },
  searchResultTagsScroller: {
    maxHeight: 22,
    marginBottom: 6,
    marginTop: 2,
  },
  searchResultTagsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingRight: 8,
  },
  searchResultTypeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(217,119,6,0.12)",
    borderWidth: 1,
    borderColor: "rgba(217,119,6,0.25)",
  },
  searchResultTypeBadgeText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#92400E",
  },
  searchResultPatronBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.2)",
    maxWidth: 180,
  },
  searchResultPatronBadgeText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#1E40AF",
  },
  searchResultAddressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  searchResultAddress: {
    fontSize: 12,
    color: COLORS.textSecondary,
    lineHeight: 16,
    flex: 1,
  },
  searchResultActionButton: {
    position: "absolute",
    top: 11,
    right: 11,
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  emptyContainer: {
    padding: SPACING.xxl,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 200,
  },
  emptyText: {
    fontSize: TYPOGRAPHY.fontSize.md,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginTop: SPACING.md,
  },
  regionFilterContainer: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: SPACING.lg,
    marginBottom: SPACING.md,
  },
  regionFilterButton: {
    flex: 1,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.xs,
    borderRadius: BORDER_RADIUS.md,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
  },
  regionFilterButtonActive: {
    backgroundColor: "#D4AF37",
    borderColor: "#D4AF37",
  },
  regionFilterText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
    color: COLORS.textSecondary,
  },
  regionFilterTextActive: {
    color: COLORS.white,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
  },
});
